/*
 * This source file was generated by the Gradle 'init' task
 */
package net.llvg.loliutils

import net.llvg.loliutils.exception.trying
import java.io.File
import kotlin.test.Test

class LoliUtilsTest {
    @Test fun someLibraryMethodReturnsTrue() {
            trying {
                    val file0 = use(File("test.txt").outputStream())
                    val file1 = File("test.txt").outputStream().using
            }
    }
}
