/*
 * This source file was generated by the Gradle 'init' task
 */
package net.llvg.loliutils

import kotlin.test.Test

class LoliUtilsTest {
        @Test fun someLibraryMethodReturnsTrue() {
        }
}
