/*
 * This source file was generated by the Gradle 'init' task
 */
package net.llvg.loliutils

import kotlin.test.Test

@Suppress("NO_EXPLICIT_RETURN_TYPE_IN_API_MODE_WARNING")
public class LoliUtilsTest {
    @Test
    public fun test() = Unit
}
